name: Build and Release Tauri Application

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      KEYSTORE_CONTENT: ${{ secrets.KEY_CONTENT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Install Tauri CLI
        run: npm install -g @tauri-apps/cli@2.0.0-rc.16

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install rustup
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: Install required system libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev nsis lld llvm libssl-dev

      - name: Set OPENSSL_DIR
        run: echo "OPENSSL_DIR=/usr/lib/x86_64-linux-gnu" >> $GITHUB_ENV

      - name: Set PKG_CONFIG_PATH
        run: echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig" >> $GITHUB_ENV

      - name: Add Rust targets
        run: |
          ~/.cargo/bin/rustup target add x86_64-pc-windows-msvc
          ~/.cargo/bin/rustup target add aarch64-linux-android
          ~/.cargo/bin/rustup target add armv7-linux-androideabi
          ~/.cargo/bin/rustup target add i686-linux-android
          ~/.cargo/bin/rustup target add x86_64-linux-android

      - name: Install cargo-xwin
        run: cargo install --locked cargo-xwin

      - name: Install Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          ndk-version: 21.4.7075529

      - name: Setup Android signing
        run: |
          cd src-tauri/gen/android
          echo "keyAlias=$KEY_ALIAS" > keystore.properties
          echo "password=$KEY_PASSWORD" >> keystore.properties
          echo "$KEY_CONTENT" | base64 -d > $RUNNER_TEMP/keystore.jks
          echo "storeFile=$RUNNER_TEMP/keystore.jks" >> keystore.properties

      - name: Build Tauri application for Android
        run: tauri build --target aarch64-linux-android

      - name: Build Tauri application for desktop
        run: tauri build --runner cargo-xwin --target x86_64-pc-windows-msvc

      - name: Upload artifacts to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            src-tauri/target/release/bundle/**/*
            src-tauri/target/android/release/app-release.apk
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          name: 🔖 ${{ github.ref }}
          body: |
            This is an automated release of the Tauri application.
          draft: false
          prerelease: false
